### ISSUE TITLE
How to use it with SystemJS?

### ISSUE THREAD

**Issue by amansharma0091** [bfwg/angular2-drag-scroll#1]

**Comment by bfwg** [comment]
Hi @amansharma0091 this is a very good question.

You have to add the package declaration in `system.conf.js`. 

For example, if you are using [angular2-starter](https://github.com/antonybudianto/angular2-starter), you need to add those few things to the config file. 

https://github.com/antonybudianto/angular2-starter/blob/master/src/systemjs.conf.js#L18
https://github.com/antonybudianto/angular2-starter/blob/master/src/systemjs.conf.js#L31
https://github.com/antonybudianto/angular2-starter/blob/master/src/systemjs.conf.js#L38

I would personally recommend moving your project from SystemJs to webpack. As you don't need to touch the configuration file as much and the entire build process will be easier for developers.

There are some good starting points.

[Angular2 CLI](https://github.com/angular/angular-cli)
[Angular2 Webpack Starter](https://github.com/angular/angular-cli)

Hope this helps.

**Comment by bfwg** [comment]
Hey @amansharma0091 , any updates?

**Comment by bfwg** [comment]
Closing due to no updates.
