### ISSUE TITLE
Not able to drag-scroll vertically

### ISSUE THREAD

**Issue by paw1** [bfwg/angular2-drag-scroll#11]
Hi.

Is there any necessary css that needs to be applied to the container that i'm making drag-scrollable?

So far I've only added "drag-scroll" and [drag-scroll-disabled]="disabled" to my container div, and I am only able to scroll horizontally. 

I can see that these cssproperties have been applied to the container :

overflow: auto;
white-space: nowrap;
display: block;

Also, my horizontal scrollbar disappears as soon as i add the drag-scroll to my div. However the vertical scroll-bar remains.

**Comment by bfwg** [comment]
Hi @paw1 thanks for reporting this, can you give me the flavour of your OS and some code about your drag-scroll component?

**Comment by paw1** [comment]
Hi @bfwg , I'm running chrome 59 on windows 10. I'm using ng2-admin template to build my webapp. I also found that setting scrollbar-hidden to true messed up my page (snapshot attached).

1. With scrollbar-hidden = TRUE :  (notice the extra container div that is applied just outside of the div with drag-scroll)

Code :
<div id="kanban-board" drag-scroll [drag-scroll-disabled]="disabled" [scrollbar-hidden]="true">

![image](https://user-images.githubusercontent.com/6694561/27479820-147d0022-5833-11e7-9f3f-b6faf409333e.png)


2. Withscrollbar-hidden = FALSE

Code :
<div id="kanban-board" drag-scroll [drag-scroll-disabled]="disabled" [scrollbar-hidden]="false">

![image](https://user-images.githubusercontent.com/6694561/27479885-699b1954-5833-11e7-877e-cdb8a3c44f02.png)

**Comment by bfwg** [comment]
In `<div id="kanban-board" drag-scroll [drag-scroll-disabled]="disabled" [scrollbar-hidden]="false">`, have you declared `disabled` and `false` in your component class? If not, it should be written this way.
`<div id="kanban-board" drag-scroll drag-scroll-disabled="disabled" scrollbar-hidden="false">`
*note: no square brackets.

**Comment by paw1** [comment]
Hi @bfwg , I have indeed defined a boolean variable 'disabled' in the component class. As for scrollbar, i think you we need to define "false", but I went ahead and changed it to ```[scrollbar-hidden]="scrollHidden"``` and defined a boolean variable scrollHidden. 

I have a suspicion that the problem lies somewhere near  the extra container div that is applied just outside of the div with drag-scroll (shown in the first image).

**Comment by bfwg** [comment]
Hi @paw1 , have you applied any css on id "kanban-board"? What happen if you wrap "kanban" in another div like the below?
```
<div drag-scroll [drag-scroll-disabled]="disabled" [scrollbar-hidden]="true">
  <div id="kanban-board" >
    ...
  </div>
</div>
```
Or wrap kanban around a div like:
```
<div id="kanban-board" >
  <div drag-scroll [drag-scroll-disabled]="disabled" [scrollbar-hidden]="true">
    ...
  </div>
</div>
```

**Comment by paw1** [comment]
Hi @bfwg , let me get back to you in some time. Currently upgrading old code to support angular 4.

**Comment by bfwg** [comment]
@paw1 no rush 😄
