### ISSUE TITLE
Error with disabled nav

### ISSUE THREAD

**Issue by azhivaeva-bmt** [bfwg/angular2-drag-scroll#14]
When I use our drag scroll with disabled nav, if I redirect to another page, I catch exception
![image](https://user-images.githubusercontent.com/26054907/27531092-11599670-5a64-11e7-8be1-e19e7975916f.png)
Please, correct it 

> ngOnDestroy() {
>     this.renderer.setElementAttribute(this.el.nativeElement, 'drag-scroll', 'false');
>     this.mouseMoveListener();
>     this.mouseDownListener();
>     if (this._nav) {
>       this.nextBtnDownListener();
>       this.prevBtnDownListener();
>     }
>   }
>

**Comment by bfwg** [comment]
Fixed in #15
