### ISSUE TITLE
Not able to select form elements inside scrollable div

### ISSUE THREAD

**Issue by fferrara** [bfwg/angular2-drag-scroll#16]
I've the following code

    <div class="editor-scroll"  drag-scroll>
      <div>
          <input type="text" [(ngModel)]="text">{{text}}
      </div>
    </div>

The drag-scroll directive doesn't allow me to select the textbox by clicking on it.

I tried this workaround and it works. Is it necessary to prevent the click events to propagate?

    onMouseDown(e: MouseEvent) {
        //e.preventDefault();   <--------- commented this
         this.isPressed = true;
        this.downX = e.clientX;
        this.downY = e.clientY;
        return true //false;   <----------- returning true
    }
    onMouseUp(e: MouseEvent) {
        //e.preventDefault();     <--------- commented this
        this.isPressed = false;
        return true //false;    <----------- returning true
      }

**Comment by bfwg** [comment]
Hi @fferrara , thanks for reporting this.

**Comment by fferrara** [comment]
thank you for the patch

**Comment by bfwg** [comment]
@fferrara np
