### ISSUE TITLE
import BrowserModule

### ISSUE THREAD

**Issue by 0nza1101** [bfwg/angular2-drag-scroll#2]
Hello man great plugin,
I would notice you, you imported BrowserModule inside angular2-drag-scroll.ts and cause of this I cant import it inside my NgModule because BrowserModule cant be loaded twice see [this](https://hassantariqblog.wordpress.com/2016/10/16/angular2-lazy-loading-in-angular2-error-browsermodule-has-already-been-loaded-if-you-need-access-to-common-directives/l).

**Comment by bfwg** [comment]
Hi @0nza1101 

I created a fix for this #3 

Uninstall the old plugin and run:
```
npm install angular2-drag-scroll@latest
```
Thanks for reporting this. Let me know if it's working for you!

**Comment by bfwg** [comment]
Hey @0nza1101 , any updates?

**Comment by 0nza1101** [comment]
Hey, yes the problem is fixed but It seems I cant use your module in my project 🤕

**Comment by bfwg** [comment]
Is there a technique issue? 😞

**Comment by 0nza1101** [comment]
No I can get your sample working but not in my project, maybe a css break or something like that

**Comment by bfwg** [comment]
@0nza1101 I'm sorry to hear that, thanks for reporting this issue.
