### ISSUE TITLE
Demo app mobile view issue

### ISSUE THREAD

**Issue by bfwg** [bfwg/angular2-drag-scroll#20]
## Summary

As a user, I want to view the demo app page on mobile device properly.

## Requirement 

Investigate and fix the issue.

**Comment by nachocoig** [comment]
First of all great job!

Any news about this issue? We have a app that uses your amazing component but no event works on mobile version.

**Comment by bfwg** [comment]
Thanks @nachocoig! It means a lot to me knowing this project is helpful to others. I have just published v1.3.6, the mobile touch issue should get resolved. Please reinstall the package and give it a try.
However if it is still not working for you, please let me know and I'll try my best to fix it.

**Comment by nachocoig** [comment]
Hello @bfwg! Thanks for posting a new version so fast. Now, your project works correctly, but, my project is broken when use your module. The problem is a click event. I think that your module captures all click events from my application and only drag works (my links is broken).

Google Chrome Developer tools says;

>  [WARN] > angular2-drag-scroll.ts:207 Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted.


Very grateful for your attention.

Regards!

**Comment by suresh2018** [comment]
@nachocoig me too face this issue ..i am also using latest  v1.3.6.

**Comment by nachocoig** [comment]
@suresh2018 Me too using v1.3.6.

At the moment, i disabled this module on mobile devices. If u want know if a determined device is mobile or not, u can use this line: 

`  let isMobile = /Android|iPhone/i.test(window.navigator.userAgent);`

**Comment by bfwg** [comment]
Thanks for the report @nachocoig @suresh2018. 
I will investigate into this issue and get it fixed as soon as possible.

**Comment by bfwg** [comment]
Let us move the conversation to #26

**Comment by bfwg** [comment]
Resolved in #31
