### ISSUE TITLE
Error using code

### ISSUE THREAD

**Issue by bobrinch** [bfwg/angular2-drag-scroll#25]
I get this error, and all other javascript on my page halts:

"Ignored attempt to cancel a touchend event with cancelable=false, for example because scrolling is in progress and cannot be interrupted."

**Comment by bfwg** [comment]
Hey @bobrinch , thanks for reporting this. Do you mid to share me with more information? Like a block of your code.

**Comment by bfwg** [comment]
Relates to #20

**Comment by bfwg** [comment]
Resolved in #27
