### ISSUE TITLE
Doesn't work on mobile having kitkat 

### ISSUE THREAD

**Issue by nidhi1612** [bfwg/angular2-drag-scroll#32]
Hi,

Thank you for your quick response and solving the issue of drag-scroll responsive behaviour. I am actually using drag-scroll in my ionic 3 app. (which uses angular 2 in the base). while i was testing it on android devices it worked like charm on lollipop and above OS versions. But app crashes for kitkat with below errors,
chromium: [INFO:CONSOLE(114671)] "Uncaught SyntaxError: Use of const in strict mode."
chromium: [INFO:CONSOLE(1)] "Uncaught ReferenceError: webpackJsonp is not defined"
, can you advice me the solution for the same.

**Comment by bfwg** [comment]
Hi @nidhi1612 , This is very likely a compatibility issue. More investigation is needed.
