### ISSUE TITLE
production build: not working with UglifyJS 

### ISSUE THREAD

**Issue by matbalazsi** [bfwg/angular2-drag-scroll#33]
Hello,
Is angular2-drag-scroll@1.3.8 compatible with angular4? I am getting the following error when building for production:

```
from UglifyJs
SyntaxError: Unexpected token: name (DragScroll) [./~/angular2-drag-scroll/src/angular2-drag-scroll.js:4,0]
```

I have read that this error might be due to compiler options. Here are mine:

```
{
    "compilerOptions": {
        "sourceMap": true,
        "rootDir": "./client",
        "module": "commonjs",
        "outDir": ".tmp",
        "removeComments": false,
        "experimentalDecorators": true,
        "target": "ES5",
         "allowJS": true
    },
    "exclude": [
      "node_modules"
    ],
    "filesGlob": [
        "client/{app,components}/**/!(*.spec).ts",
        "typings/browser.d.ts"
    ],
    "awesomeTypescriptLoaderOptions": {
      "resolveGlobs": true,
      "forkChecker": true
    }
}
```

**Comment by bfwg** [comment]
Hey @matbalazsi  thanks for reporting this, what is the build command that you are using?

**Comment by matbalazsi** [comment]
I using generator-angular-fullstack@alpha, but upgraded to Angular4 
[https://github.com/angular-fullstack/generator-angular-fullstack](url)

The command I am using is gulp build, which uses webpack@1.15.0.

**Comment by bfwg** [comment]
I see, have you tried [Angular CLI](https://github.com/angular/angular-cli)? It is the official tool for generating starter projects. You can copy the **server** folder from `generator-angular-fullstack` and integrate with the project generated by the CLI.

**Comment by bfwg** [comment]
@matbalazsi 

Any luck?
