### ISSUE TITLE
Doesn't trigger CSS scroll-snap

### ISSUE THREAD

**Issue by joejordanbrown** [bfwg/angular2-drag-scroll#4]
This doesn't work with the CSS scroll-snap, It's currently only a FireFox, Safari and Edge feature so will need to be viewed on one of them browsers since I've not added a polyfill.

Plunker Demo below
http://embed.plnkr.co/muToSNDeqz94rHX4yNJZ/

**Comment by bfwg** [comment]
@joejordanbrown Thanks for the feedback, the Plunker Demo link is not working for me.

**Comment by joejordanbrown** [comment]
@bfwg I've updated the link, that must have been a temp URL I added before. 

I'm unsure if this actually could be a problem with browsers implementation of this CSS feature. I've been playing around and notice it doesn't trigger when using JavaScript scrollTop, scrollTo etc. The documentation for this feature is still very basic. I will look into it further and see if it needs an event triggerd to work correctly.

The specs are here that mention scroll functionality https://www.w3.org/TR/css-scroll-snap-1/#scroll-types

**Comment by bfwg** [comment]
I see, so it needs a mouse action to trigger. If you found a way to make this work, a PR is more than welcome!

**Comment by bfwg** [comment]
@joejordanbrown I'm going to close this issue. If you feel this needs to be reopen again, let me know.

**Comment by bfwg** [comment]
I'm going to implement the snap functionality.

**Comment by joejordanbrown** [comment]
@bfwg sounds good, will you be creating a custom implementation using mouse events to work across all browsers since Chrome still haven't got scroll snap? I created my own a while back, I'd have to see if I can find the code, I don't think I pushed it to GitHub.

http://caniuse.com/#search=snap

Also, it would be a good idea to refactor using [Renderer2](https://angular.io/api/core/Renderer2) and also refactor all the native element sections to use the renderer.

from
`this.el.nativeElement.style.height = '100%';`
to
`this.renderer.setStyle(this.el.nativeElement, 'height ', '100%');`

and remove any direct dom manipulation.

this would need changing
```
  private hideScrollbar(): void {
    if (this.el.nativeElement.style.display !== 'none' && !this.wrapper) {
      this.parentNode = this.el.nativeElement.parentNode;
      this.wrapper = document.createElement('div');
      this.wrapper.style.width = this.el.nativeElement.offsetWidth + 'px';
      this.wrapper.style.height = this.el.nativeElement.offsetHeight + 'px';
      this.wrapper.style.overflow = 'hidden';
      this.el.nativeElement.style.width = `calc(100% + ${this.scrollbarWidth})`;
      this.el.nativeElement.style.height = `calc(100% + ${this.scrollbarWidth})`;
      // set the wrapper as child (instead of the element)
      this.parentNode.replaceChild(this.wrapper, this.el.nativeElement);
      // set element as child of wrapper
      this.wrapper.appendChild(this.el.nativeElement);
    }
  }
```

from 
```
this.wrapper = document.createElement('div');
```
to
```
this.wrapper = this.renderer.createElement('div');
```


This part will be a problem and would need to be changed because as far as I know, the renderer can't touch `parentNode`

```
// set the wrapper as child (instead of the element)
this.parentNode.replaceChild(this.wrapper, this.el.nativeElement);
```
Could you explain the reason for this? I'm sure there would be an alternative way to do this that will work with the renderer.

I can help with refactoring to use `Renderer2` and create some pull requests.

**Comment by bfwg** [comment]
@joejordanbrown Yes, this is a very good idea! 
`this.parentNode` is used when we want to hide the scrollbar. 
To hide the scroll bar, we need to create a new wrapper div and insert the div between the parent div and the carousel div.

For example:
This is a normal carousel
![image](https://user-images.githubusercontent.com/12819525/30182916-5afda62a-93cd-11e7-95ae-265ee1eb0368.png)

When we try to hide the scrollbar, there is no magic! We simply create a wrapper div, and set the size of that wrapper div as the same as container div but minus its scrollbar width/height.

![image](https://user-images.githubusercontent.com/12819525/30183140-2909d1b0-93ce-11e7-98f6-3a60ad1e6812.png)


Finally, we detach the container div, attach the wrapper div to parent div and insert the container div back to the wrapper div.
![image](https://user-images.githubusercontent.com/12819525/30183187-5ef4d5ea-93ce-11e7-87b2-0e82505d2972.png)


Since the wrapper's overflow attribute has been set to 'hidden', the scrollbars are no longer shown.
I hope my drawing skill is still up to the game 😛 

I'm still working on the snap functionality at the moment, it will be controlled fully using javascript. This will allow the cross browser compatibility.

A PR for the refactor is more than welcome, but I would suggest to wait until the snap functionality PR is merged.

Thanks again!

**Comment by joejordanbrown** [comment]
@bfwg 

Thanks for great diagrams, it helped me visualise it without digging into the code too much.

I've created an example of how we can use a component with `<ng-content></ng-content>` so we can remove the need for `parentNode` and stick to a more Angular way of manipulating the dom using `Renderer2` so it will work with server side rendering and other environments that don't have direct DOM access. 

You can see an example here https://stackblitz.com/edit/angular-drag-scroll?file=app%2Fdrag-scroll.component.ts it's a stripped back example just to show the wrapper div refactor that would make it possible to use the renderer.

But yes sure, if you think the wrapper DOM manipulation change is fine then I'll create a PR once you've finished with the scroll snap functionality.

**Comment by bfwg** [comment]
@joejordanbrown 

The demo looks amazing! 
#34 is in, give the snap functionality a try! 

Looking forward for your refactor PR.

**Comment by joejordanbrown** [comment]
@bfwg 

Thanks. I've just taken a look, it looks great. I found one bug though when you drag to the end it snaps back to the first one in view.

I'll get to work on refactoring it over the weekend. I'll also create a demo using server side rendering and service workers and upload to my server to show a server side rendering example.

Should I include the server side code in the main demo and add it into `angular-cli.json` as `apps[1]`?

**Comment by bfwg** [comment]
@joejordanbrown Sounds good, looking forward to it.
I'm not sure if that is a bug as drag will always try to snap to the left most item in the view by default.

There are definitely more work that needs to be done for the snap functionality.

**Comment by joejordanbrown** [comment]
@bfwg 

My thought that scroll snapping would snap to the side that you're scrolling to. So if you drag left to scroll right it would snap on the right side of the inner elements and vice versa. I think that's a more natural feel with the user experience. I would be interested to check if that's how the scroll snap spec is described for browsers to implement. I'll do some research to see how they think it should work since I'm sure that this must have been discussed when they wrote the specs.

I've taken a look at how you are manipulating the children elements using `nativeElement.children`, the problem with this is that it's not possible to use the renderer. The best approach for this is to create a directive that is attached to each child element with the selector `dragScrollStep` and you then use `@ViewChildren(DragScrollStep) steps: QueryList<DragScrollStep>;` 

Without server side rendering the Angular app wouldn't be SEO friendly or Share friendly. View the page source and you will see the code being rendered on the server which adds the title, meta data, open graph data. Plus the site works on devices with JavaScript disabled. It can fetch all HTTP requests on the server before being sent to the person, helps with slow internet connections. The list goes on the benefits of server side rendering.

**A few examples:**

### Server Side rendering + Service Workers Angular App
https://nodejs.uixd.co.uk/
[Sharing Debugger Results](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fnodejs.uixd.co.uk%2F)

https://nodejs.uixd.co.uk/examples/http
[Sharing Debugger Results](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fnodejs.uixd.co.uk%2Fexamples%2Fhttp)


### Standard Angular App
https://material.angular.io/
[Sharing Debugger Results](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fmaterial.angular.io%2F)

https://material.angular.io/components/datepicker/overview
[Sharing Debugger Results](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fnodejs.uixd.co.uk%2F)

See my GitHub for the example of the server side rendering above https://github.com/joejordanbrown/angular-cli-universal It's a normal Angular Cli App with a few more files to add server side rendering bootstrapping and adding the entry point to `app[1]`  in the`angular-cli.json` and when building you build app[0] and app[1] and run the node server to renderer the pages on the fly.

**Comment by bfwg** [comment]
@joejordanbrown 

Thanks for the clearfication!

Definitely we want to utilize Renderer as much as possible to make this library more "Angular".

Do you know if angular universal works on other backend frameworks like spring?

**Comment by bfwg** [comment]
@joejordanbrown 
I have fixed a few bugs in #35

**Comment by joejordanbrown** [comment]
@bfwg 

I've worked through a lot of the code and refactored it nearly all to use the renderer2 where possible. I've changed how it's now a component and using `ng-content`, It uses a directive for `@ContentChildren` for the snap steps. That all works fine. I'm now going through the code adding `isPlatformBrowser` and `isPlatformBrowser` where necessary to be SSR compatible. Once I've tested that is working I will push the branch for you to review and test.

Atm, It's just them two but they are talking about bringing many different engines out that connect with different backends. I'm not so familiar with Spring, I know it's Java related framework that's about it. Is that what you're currently using with Angular? This issue may be of use to you https://github.com/angular/universal/issues/280 it;s related to Universal + Spring.

Cool, I'll look at pulling them fixes into the branch I'm working on.

**Comment by bfwg** [comment]
@joejordanbrown 

Thanks for the reference, I use spring-boot for work. I'm an express fan, but I also use spring for one of my projects' backend. 

There must be a lot refactor code changes that you have go through. Can't wait to review your work!

**Comment by joejordanbrown** [comment]
@bfwg 

Sorry for the very late reply. I've been away and not had internet access. 

I will refactor them changes urgently this week and push them so we can move forward with this.

**Comment by bfwg** [comment]
@joejordanbrown 

No worries, I'm pretty busy the past few weeks as well.

**Comment by bfwg** [comment]
@joejordanbrown I'm going to close this issue since the refactor ticket is in.
