### ISSUE TITLE
Any chance of seeing a value?

### ISSUE THREAD

**Issue by alucardu** [bfwg/angular2-drag-scroll#44]
I want to use the drag-scroll component to display a certain value. Like the primeng slider does > https://www.primefaces.org/primeng/#/slider. Is there already something like that available if not, can I request it?

**Comment by bfwg** [comment]
Hi @alucardu, Thanks for the idea. This library only focus on the carousel aspect. Sliders in my opinion is a different topic and should not be covered in this library.
