### ISSUE TITLE
scrollbarHidden not working

### ISSUE THREAD

**Issue by MSkraburski** [bfwg/angular2-drag-scroll#45]
Hi, I've been using your files since yesterday but cannot overcome an issue concerning hidden scrollbar. Can you help ? Would be extremely grateful. Here is a part of  code:

> <div class="demo-border" style="">
        <div class="demo-one"
             drag-scroll
             [scrollbar-hidden]='true'
             (leftBound)="leftBoundStat($event)"
             (rightBound)="rightBoundStat($event)"
             #nav
             style="width: 60%; margin-left: 20%;"
        >
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
            <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>

        </div>
    </div>

Regards,
Mikołaj

**Comment by MSkraburski** [comment]
I'll just add that the button actions work properly.

**Comment by bfwg** [comment]
Hi @MSkraburski , have you tried setting a height for the image container? Like:
```javascript
    <div class="demo-one"
         drag-scroll
         [scrollbar-hidden]='true'
         (leftBound)="leftBoundStat($event)"
         (rightBound)="rightBoundStat($event)"
         #nav
         style="width: 60%; height: 300px;"
    >
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>
        <img id="fota" class="img-circle" src="../../assets/img/faces/marc.jpg"/>

    </div>
```

**Comment by MSkraburski** [comment]
Well it turned out this plugin is deprecated in Angular 2 therefore I could not get the functions I wanted. Cheers

**Comment by bfwg** [comment]
Yes, the current library angular version is 4.3.6. Thanks for reporting this.
