### ISSUE TITLE
Doesn't work on touch devices.

### ISSUE THREAD

**Issue by zz-mike** [bfwg/angular2-drag-scroll#48]
Hello,
seems that scroll by drag doesn't work on touch devices.
Is it a bug or just a limitation?

**Comment by suresh2018** [comment]
It's working good for me..also mobile

**Comment by bfwg** [comment]
Hey @zz-mike 
Can you provide more information and possibly a code block?

**Comment by Bidthedog** [comment]
I've ran into this too. I expect "touchstart" and "touchend" need to be implemented as well as "mouseup" and "mousedown" to support mobile / touch devices.

Suggest adding the touch events [here](https://github.com/bfwg/angular2-drag-scroll/blob/db8244bbb613fc85928fe0aed20278df3ac60247/src/angular2-drag-scroll.ts#L144)

"click" can't be used as the component uses three states, so there'll be a little bit of duplication.

**Comment by bfwg** [comment]
Hey @Bidthedog 

Thanks for reporting this. The scroll event on a device is equivalent to drag event on a browser. We could add a onTouch listener to the library, but that is just going to overlap with the default scroll event on devices.
Are you able to scroll your carousel view on a device? If so, you should be able to drag it.

**Comment by Bidthedog** [comment]
The only way I can scroll on a mobile device is by calling `moveTo`, `moveLeft` or `moveRight`, swiping or press+drag doesn't move the carousel at all. The same behaviour occurs in Chrome DevTools mobile, so I've been able to record a gif demonstrating how I'm using it:

![angular2-drag-scroll](https://user-images.githubusercontent.com/1425696/32272662-f9c276ec-bef6-11e7-94b6-7a983248770e.gif)

Weirdly, I've just tried your demo app and that works... I did notice that the elements inside my drag-scroll component needed to be made full-size (so they fit exactly in the drag-scroll component) before scrolling would work. I've also had only limited success with the `scrollbar-hidden` directive, so I turned that off and used `overflow: hidden !important;` in CSS instead. Not sure if that has anything to do with it.

**Comment by Bidthedog** [comment]
Well, that's interesting. I just removed my custom CSS and it works. Which leads me to what I believe is the real issue: the `scrollbar-hidden` directive doesn't seem to actually remove the scrollbar. Inspecting the generated HTML, it seems that the directive is duplicating the component root:

```
<div _ngcontent-c4=""
     class="ng-tns-c4-0"
     drag-scroll=""
     id="tech-list"
     scrollbar-hidden="true"
     style="overflow: hidden; white-space: nowrap;">
  <div _ngcontent-c4=""
       class="ng-tns-c4-0 ng-trigger ng-trigger-listAnimation"
       drag-scroll="true"
       id="tech-list"
       scrollbar-hidden="true"
       style="overflow: auto; white-space: nowrap; width: 100%; height: calc(100% + 17px); display: block;"
       ng-reflect-scrollbar-hidden="true">
    <!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}-->
    <div _ngcontent-c4=""
         class="tech-cell ng-tns-c4-0"
         title="xUnit.net (double click to visit https://xunit.github.io/)">
      <img _ngcontent-c4=""
           class="img-responsive center-block"
           src="assets/img/tech/xunit.png"
           alt="xUnit.net">
    </div>
  </div>
</div>

```

I'm using the #tech-list selector in my CSS to add margins to the carousel - so my margins are duplicated, and the new INNER tech-list is set to overflow: auto, so the scrollbar is shown:

```
  #tech-list {
    // overflow: hidden !important;
    margin: 0px 50px;
    // cursor: pointer;

    .tech-cell {
      display: inline-block;
      text-align: center;
      vertical-align: middle;

      img {
        display:inline-block;
        padding: 10px 5px;
      }
    }
  }
```

I think I can get around this by adding another container outside the tech-list element for styling. It's a bit of a weird way to implement overflow:none, though I'm sure you have your reasons!

**Comment by Bidthedog** [comment]
OK, I added the container, but I'm still getting scroll bars. The generated HTML looks like this:

```
<app-tech-list _ngcontent-c3=""
               _nghost-c4=""
               class="ng-tns-c4-0"
               ng-reflect-tech="[object Object],[object Object">
  <div _ngcontent-c4=""
       class="ng-tns-c4-0"
       id="tech-list-container">
    <div _ngcontent-c4=""
         class="ng-tns-c4-0"
         id="tech-list">
      <div _ngcontent-c4=""
           class="ng-tns-c4-0"
           drag-scroll=""
           scrollbar-hidden="true"
           style="overflow: hidden; white-space: nowrap;">
        <div _ngcontent-c4=""
             class="ng-tns-c4-0 ng-trigger ng-trigger-listAnimation"
             drag-scroll="true"
             scrollbar-hidden="true"
             style="overflow: auto; white-space: nowrap; width: 100%; height: calc(100% + 17px); display: block;"
             ng-reflect-scrollbar-hidden="true">
          <!--bindings={
  "ng-reflect-ng-for-of": "[object Object],[object Object"
}-->
          <div _ngcontent-c4=""
               class="tech-cell ng-tns-c4-0"
               title="ASP.Net MVC (double click to visit https://www.asp.net/mvc)">
            <img _ngcontent-c4=""
                 class="img-responsive center-block"
                 src="assets/img/tech/aspnet_mvc.png"
                 alt="ASP.Net MVC">
          </div>
        </div>
      </div>
    </div>
  </div>
</app-tech-list>
```

Seems that `overflow: hidden` is added to the first component element, but the newly generated child has `overflow: auto`?

**Comment by Bidthedog** [comment]
Last bit of info - I can "hide" the inner scrollbar with the following CSS, but this disables touch / swipe actions:

```
  div[drag-scroll] {
    overflow: hidden !important;
  }
```

So there are potentially two issues that confuse the "touch screen" issue here:

1. The `id` attribute shouldn't be duplicated when `scrollbar-hidden` is used (not valid HTML, and this confuses CSS when using an id selector).
2. The scrollbar doesn't seem to hide properly when `scrollbar-hidden` is specified - the inner element uses `overflow: auto`, but without this it doesn't drag on touch / mobile devices. This could have something to do with my CSS / layout, but I'm struggling to identify it if it is.

**Comment by bfwg** [comment]
Hey @Bidthedog ,

The duplicate wrapper container is expected. To hide the scroll bar, we need to create a new wrapper div and insert the div between the parent div and the carousel div.

For example:
This is a normal carousel
![image](https://user-images.githubusercontent.com/12819525/30182916-5afda62a-93cd-11e7-95ae-265ee1eb0368.png)

When we try to hide the scrollbar, there is no magic! We simply create a wrapper div, and set the size of that wrapper div as the same as container div but minus its scrollbar width/height.

![image](https://user-images.githubusercontent.com/12819525/30183140-2909d1b0-93ce-11e7-98f6-3a60ad1e6812.png)


Finally, we detach the container div, attach the wrapper div to parent div and insert the container div back to the wrapper div.
![image](https://user-images.githubusercontent.com/12819525/30183187-5ef4d5ea-93ce-11e7-87b2-0e82505d2972.png)


Since the wrapper's overflow attribute has been set to 'hidden', the scrollbars are no longer shown.

If you want to add custom css to your carousel, please make sure that is doesn't have any conflict with the css in the carousel. You can find examples in the demo app for how to style your carousel.

Thanks

**Comment by Bidthedog** [comment]
@bfwg Much appreciated for the detailed explanation - I figured it was something like that after I noticed that overflow: auto adds scrollbars when scrolling.

I'll check my CSS and see what I've done wrong :)

**Comment by Bidthedog** [comment]
For anyone else experiencing the same issue, all I was missing was the forced height on the drag-scroll element:

```
    #tech-list {
      height: 160px; // required to hide scrollbars
    }
```

I still believe there is an issue with the `id` attribute being duplicated for the generated div, as it produces invalid HTML.
