### ISSUE TITLE
Sample code using drag-scroll in parent component to scroll children 

### ISSUE THREAD

**Issue by augustbend** [bfwg/angular2-drag-scroll#49]
I'd like to implement something along these lines:

---Angular Template---
```
<div drag-scroll>
  <app-card></app-card>
</div>

```
---Browser Render---
```
<div drag-scroll>
  <app-card>
    <div class='card-single'></div>
    <div class='card-single'></div>
    <div class='card-single'></div>
  </app-card>
</div>
```

I think I must apply the plugin to a DOM element, hence use the @tommykamkcm code, but it does not work. Is there any sample implementations that I can use as reference for this? Or can you give me some suggestions on how to proceed?

Thanks

**Comment by bfwg** [comment]
Hi @augustbend 

The fastest way for me to know what is going on is to run your code.
Can you fork this repository and append the `app-card` (with the needed library) to the demo app. Paste the link here after you are done and I can take a closer look.

Thanks.
