### ISSUE TITLE
file not found

### ISSUE THREAD

**Issue by Douglasfeuser** [bfwg/angular2-drag-scroll#5]
I'am testing, a new app and needed a similar function like dragscroll.
But i can't get this one to work, i get the following error.
I'am using ionic 2 framework.

Module build failed: Error: ENOENT: no such file or directory, open 'C:\ionic2\edigital-app\node_modules\angular2-drag-scroll\src\angular2-drag-scroll.js.map'

**Comment by bfwg** [comment]
@Douglasfeuser , thanks for reporting, I'll put up a fix for this soon.

**Comment by bfwg** [comment]
@Douglasfeuser Is it working fine now?

**Comment by Douglasfeuser** [comment]
Yes it's working now. Thanks
