### ISSUE TITLE
Allow to not snap to current child

### ISSUE THREAD

**Issue by santialbo** [bfwg/angular2-drag-scroll#50]
Could you add an option to disable snapping to the current child?
The way we were using it this directive is with a big element that contained everything. The fact that we only have one child makes this directive go to the start everytime we scroll.

**Comment by bfwg** [comment]
Hi @santialbo 

Like a `snap-disabled` attribute that disable snap functionality for all children?

**Comment by santialbo** [comment]
Yes, I don't mind and long as I'm able to disable the feature (which I think it's cool, it's just that it doen't work on my case).
Thanks a lot for the good work and for open sourcing it :)

**Comment by bfwg** [comment]
@santialbo 
You are welcome, I have published 1.4.1 which introduces the `snap-disabled` attribute.
