### ISSUE TITLE
multiple elements

### ISSUE THREAD

**Issue by Nahask** [bfwg/angular2-drag-scroll#53]
Hi,

First of all thanks for your great work :).

I'm currently trying to pu multiple elements within the drag-scroll div doing like this
![image](https://user-images.githubusercontent.com/7364650/31452163-6fe7c164-aeae-11e7-97ef-8c0d89330be1.png)
but when i'm doing this, instead of being on the same row, each elements is on is own row
and i got this result (i raised the height so you could  see)
![image](https://user-images.githubusercontent.com/7364650/31452237-9e21d0d8-aeae-11e7-9e8e-c3c8e05a4119.png)

I don't really know if i'm missing something or if it's normal at the moment,

regards : )

**Comment by bfwg** [comment]
Hi @Nahask ,

The image element has a predefined [dimension](https://github.com/bfwg/angular2-drag-scroll/blob/develop/demo/app/home/home.component.css#L11). You need to set the width and height of your children elements.
For example.
```html
    <div class="demo-one"
      drag-scroll
      drag-scroll-y-disabled="true"
      scrollbar-hidden="true"
      (reachesLeftBound)="leftBoundStat($event)"
      (reachesRightBound)="rightBoundStat($event)"
      #nav
      >
      <div style="display:inline-block; height: 260px; width: 260px;" 
        *ngFor="let image of imagelist">
        <img [src]="'assets/img/' + image" (click)="clickItem(image)"/>
        <div>{{image}}</div>
      </div>
    </div>
```

Best Regard

**Comment by Nahask** [comment]
ho ok thank you : ) i don't know how i missed that :x

**Comment by bfwg** [comment]
Glad I can help 😄
