### ISSUE TITLE
Can we have a new version 1.4.4 

### ISSUE THREAD

**Issue by akkumar** [bfwg/angular2-drag-scroll#67]
Can we have a minor release 1.4.4 that can pull in Issues #62 , #63 , #64 , #65 . ( Especially #64 ) to make sure versions are indeed in sync as we include in other projects as well.  It would be useful to have one. Thanks in advance.

**Comment by bfwg** [comment]
Yes, sorry for the delay. 1.4.4 is published on commit db8244bbb613fc85928fe0aed20278df3ac60247. 🎉
