### ISSUE TITLE
DragScrollModule fails to load with angular cli 1.5.0

### ISSUE THREAD

**Issue by marayfirth** [bfwg/angular2-drag-scroll#69]
After upgrading to Angular 5.0 and Angular CLI 1.5, I get an error with ng serve.

```
ERROR in ./node_modules/angular2-drag-scroll/src/angular2-drag-scroll.ts
Module build failed: Error: C:\Dev\OrderingSystem\client\node_modules\angular2-drag-scroll\src\angular2-drag-scroll.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (C:\Dev\OrderingSystem\client\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:629:23)
    at plugin.done.then (C:\Dev\OrderingSystem\client\node_modules\@ngtools\webpack\src\loader.js:467:39)
    at process._tickCallback (internal/process/next_tick.js:109:7)
 @ ./node_modules/angular2-drag-scroll/index.js 3:29-66
 @ ./src/app/venue/venue.module.ts
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.
```
Version of angular2-drag-scroll: 1.4.4

Might be related to this one : angular/angular-cli#8263 
I reproduce when not setting aot though.

**Comment by MonasteryJohn** [comment]
Seems to be related to https://github.com/angular/angular-cli/issues/8284 due to ts files being in the dist. Many people are having this issue with lots of packages after the upgrade to angular5. 

I've been able to work around this for now by modifying my src/tsconfig.app.json to have the files the compiler is complaining about the in the "includes" array. If you check the link they recommend against this, but it should work until these libraries are updated.

**Comment by bfwg** [comment]
1.4.5 is out with the fix. Thanks guys!

**Comment by akkumar** [comment]
@marayfirth  - I have put in a fix here at #75 .

It would involve pointing angular2-drag-scroll to the following:
```json
"angular2-drag-scroll": "git@github.com:akkumar/angular2-drag-scroll.git#d9e880e3d74988253846e5caec6625e0d78351c7"
```

Can you help check if that fix works and report issues if any ?  Thanks in advance

**Comment by marayfirth** [comment]
@akkumar it seems ok on my side with this version.

**Comment by akkumar** [comment]
@marayfirth - Thanks for confirming. Also to help - can you add your npm version and node version, in which this works ?

@bfwg - May be - we can just cut a release 1.5.0 with the PR #75 and debug it later if needed :)

**Comment by bfwg** [comment]
1.5.0 is out with #75 , thanks guys!
