### ISSUE TITLE
Does not compile on latest @angular/cli

### ISSUE THREAD

**Issue by MrSnappingTurtle** [bfwg/angular2-drag-scroll#72]
Hi, I created a new project with the 1.5.0 version of `@angular/cli` (`ng new angular2-drag-scroll-test`). I then installed the 1.4.5 version of `angular2-drag-scroll` (`npm i --save angular2-drag-scroll`). I imported it into `app.module.ts` and ran `ng serve`. However, it doesn't compile with the following error:

```
$ ng serve
** NG Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **
Date: 2017-11-11T00:18:31.492Z                                                          
Hash: bf521d7c8c1f36b5208d
Time: 5184ms
chunk {inline} inline.bundle.js (inline) 5.79 kB [entry] [rendered]
chunk {main} main.bundle.js (main) 21.4 kB [initial] [rendered]
chunk {polyfills} polyfills.bundle.js (polyfills) 555 kB [initial] [rendered]
chunk {styles} styles.bundle.js (styles) 33.9 kB [initial] [rendered]
chunk {vendor} vendor.bundle.js (vendor) 7.03 MB [initial] [rendered]

ERROR in ./node_modules/angular2-drag-scroll/index.ts
Module build failed: Error: /Users/dennissubachev/projects/angular2-drag-scroll-test/node_modules/angular2-drag-scroll/index.ts is not part of the compilation output. Please check the other error messages for details.
    at AngularCompilerPlugin.getCompiledFile (/Users/dennissubachev/projects/angular2-drag-scroll-test/node_modules/@ngtools/webpack/src/angular_compiler_plugin.js:629:23)
    at plugin.done.then (/Users/dennissubachev/projects/angular2-drag-scroll-test/node_modules/@ngtools/webpack/src/loader.js:467:39)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
 @ ./src/app/app.module.ts 9:0-56
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

webpack: Failed to compile.
```

Apologies in advance if this issue is better suited to be posted on the `@angular/cli` project.

**Comment by marayfirth** [comment]
Same for me. I thought it would have been fixed with #69

**Comment by bfwg** [comment]
@akkumar ^^^ thoughts?

**Comment by bfwg** [comment]
I can't seem to reproduce, I'm on a Mac(CLI version: 1.5.0). I'm able to run `ng serve` with no error after `npm run clean && npm install`.

**Comment by akkumar** [comment]
Ignoring the .ts while packing, while still including .d.ts seems to do the job. More details in #75 .

It would be great if we get a 1.5.0 with this.

**Comment by akkumar** [comment]
@MrSnappingTurtle - I have put in a fix here at #75 .

It would involve pointing angular2-drag-scroll to the following:
```json
"angular2-drag-scroll": "git@github.com:akkumar/angular2-drag-scroll.git#d9e880e3d74988253846e5caec6625e0d78351c7"
```

Can you help check if that fix works and report issues if any ?  Thanks in advance

**Comment by MrSnappingTurtle** [comment]
@akkumar Just tried it out, works great!

**Comment by bfwg** [comment]
1.5.0 is published!
@MrSnappingTurtle @marayfirth Thanks for your input.
@akkumar Thanks for the awesome work.
