### ISSUE TITLE
Versioning of releases - major / minor

### ISSUE THREAD

**Issue by akkumar** [bfwg/angular2-drag-scroll#73]
First of all - thanks a lot for getting ng5 #70 and #71 branch onto master and cutting a new release - 1.4.5 . 

Couple of suggestions though: 

* Given the major upgrade from ng dependency 4.x to 5.x - may be, we can simply call it 1.5.0 or something similar, to signify the same. (1.4.4 -> 1.4.5 does not convey the nature of changes made under the hood - sounds too innocent before it bombs on the user :) ). 

* A changelog.md would be useful with a brief mention on what went in. To quickly help. 

@bfwg  - FYI . would be useful to get your thoughts on the same.

**Comment by bfwg** [comment]
@akkumar Agreed, that totally make sense to me.

**Comment by akkumar** [comment]
closing this issue as already addressed in #74
