### ISSUE TITLE
Cannot find module 'angular2-drag-scroll'

### ISSUE THREAD

**Issue by alonstar** [bfwg/angular2-drag-scroll#78]
After installing angular2-drag-scroll, I can see angular2-drag-scroll directory under node_modules, but I can't import module from angular2-drag-scroll.

It tells me that Cannot find module 'angular2-drag-scroll'

I'm using Angular 5.0

Please help me, thank you.

**Comment by marayfirth** [comment]
Indeed, there are missing .d.ts and js files in the published npm.

**Comment by aziz-haddad** [comment]
same issue here

**Comment by akkumar** [comment]
does the issue persist with this release ? 

```json
    "angular2-drag-scroll": "1.5.0"
```
if so - can you let know the node and npm version as well.

**Comment by marayfirth** [comment]
Yes, I upgraded to this version earlier today and I got the failure at this time. Occuring with node 6.11.0 and npm 5.5.1

**Comment by akkumar** [comment]
seems like index.d.ts and angular2-drag-scroll.d.ts are missing from the release ? 

May be - a missing 'npm prepare' before the release process as the prepare process generates the .d.ts files as reported missing here in the following tree ? 

cc @bfwg .

```console
 tree -L 10 node_modules/angular2-drag-scroll/
node_modules/angular2-drag-scroll/
├── CHANGELOG.md
├── index.metadata.json
├── LICENSE
├── package.json
├── README.md
└── src
    ├── angular2-drag-scroll.metadata.json
    ├── drag-scroll-item.metadata.json
    ├── drag-scroll.metadata.json
    ├── index.metadata.json
    ├── interface
    │   ├── drag-scroll-option.d.ts
    │   ├── drag-scroll-option.js
    │   ├── drag-scroll-option.js.map
    │   └── drag-scroll-option.metadata.json
    └── tsconfig.json
```

**Comment by bfwg** [comment]
@akkumar Looks like I was using npm@3.x while doing the publish command. Version 1.5.1 is out with the re-publish. Let me know if this fix the issue.

**Comment by marayfirth** [comment]
@bfwg it looks fine now

**Comment by bfwg** [comment]
Great, closing now. Thanks again for reporting this.
