### ISSUE TITLE
Compilation error - Not part of the compilation output

### ISSUE THREAD

**Issue by yluijten** [bfwg/angular2-drag-scroll#79]
Since I've upgraded to `Angular 5.x` I get the following error when building my project:

`Module build failed: Error: ..\node_modules\angular2-drag-scroll\src\angular2-drag-scroll.ts is not part of the compilation output.
`

Does the project support the latest version of Angular?

**Comment by akkumar** [comment]
does the issue persist with this release ?

```json
    "angular2-drag-scroll": "1.5.0"
```
if so - can you let know the node and npm version as well.

**Comment by yluijten** [comment]
Thanks, @akkumar.

I upgraded to the latest version, but another error appears. It looks like the `DragScrollModule` is gone. Unable to import it.

**Comment by akkumar** [comment]
@yluijten - npm / node versions ?

**Comment by akkumar** [comment]
Issue #78 - similar issue. see details.

**Comment by bfwg** [comment]
1.5.1 should resolve this issue.

**Comment by yluijten** [comment]
@akkumar, @bfwg 
Version 1.5.1 resolved the issue. Thanks.

**Comment by bfwg** [comment]
Fantastic.
